name: Build OpenRGB-RAM (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual runs

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Install dependencies
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          choco install ninja
          choco install mingw
          choco install qt5-default
          choco install git

      - name: Configure and build OpenRGB-RAM
        run: |
          cd ${{ github.workspace }}/OpenRGB-RAM  # Navigate to the root OpenRGB-RAM directory
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" ../dependencies/hueplusplus-1.2.0  # Point to correct CMakeLists.txt in the submodule directory
          mingw32-make -j4

      - name: Upload compiled OpenRGB-RAM
        uses: actions/upload-artifact@v4
        with:
          name: OpenRGB-RAM-Windows
          path: ${{ github.workspace }}/OpenRGB-RAM/build/OpenRGB.exe
