name: Build OpenRGB (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual runs

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1

      - name: Debug: Check repository structure
        run: dir

      - name: Install dependencies
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        
      - name: Configure and build OpenRGB
        run: |
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" ..
          mingw32-make -j4

      - name: Upload compiled OpenRGB
        uses: actions/upload-artifact@v4
        with:
          name: OpenRGB-Windows
          path: build/OpenRGB.exe
