name: Build OpenRGB (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1

      - name: Install dependencies
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          choco install ninja
          choco install mingw
          choco install qt5-default
          choco install git

      - name: Configure and build OpenRGB
        run: |
          cd OpenRGB  # Make sure we're in the correct folder
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" ..
          mingw32-make -j4

      - name: Upload compiled OpenRGB
        uses: actions/upload-artifact@v4
        with:
          name: OpenRGB-Windows
          path: OpenRGB/build/OpenRGB.exe
