name: Build OpenRGB for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up MinGW
    - name: Set up MinGW
      uses: msys2/setup-msys2@v2
      with:
        update: true

    # Install dependencies
    - name: Install dependencies
      run: |
        pacman -S --noconfirm mingw-w64-x86_64-cmake
        pacman -S --noconfirm mingw-w64-x86_64-make
        pacman -S --noconfirm mingw-w64-x86_64-gcc

    # Clone OpenRGB repository
    - name: Clone OpenRGB repository
      run: |
        git clone https://github.com/CalcProgrammer1/OpenRGB.git
        cd OpenRGB
        git submodule update --init --recursive

    # Configure and build OpenRGB
    - name: Configure and build OpenRGB
      run: |
        cd OpenRGB-RAM
        mkdir build
        cd build
        cmake -G "MinGW Makefiles" ../dependencies/hueplusplus-1.2.0
        mingw32-make -j4

    # Run tests or build validation (optional)
    - name: Validate build
      run: |
        cd OpenRGB-RAM/build
        ./OpenRGB.exe --version

    # Upload artifact (optional)
    - name: Upload OpenRGB build artifact
      uses: actions/upload-artifact@v2
      with:
        name: OpenRGB-Build
        path: OpenRGB-RAM/build/OpenRGB.exe
